apiVersion: argoproj.io/v1alpha1
kind: Rollout 
metadata:
  name: apache-wp
  labels:
    app: apache-wp
    type: front-end
spec:
  replicas: 1
  selector:
      matchLabels:
        type: front-end
  template:
    metadata:
      name: wordpress
      labels:
        app: apache-wp
        env: production
        type: front-end
    spec:
      containers:
        - name: apache-php
          image: bitbull/webserver
    ports:
        - containerPort: 80
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
# --- Everything above this comment are the same as a deployment ---
    blueGreen: # A new field for the Blue Green strategy options
      previewService: apache-wp # Reference to a service
      activeService: apache-wp # Reference to a service

